services:
  api:
    image: registry.arfima.com/arfima/arfima/uglydata:latest
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    working_dir: /code
    # command: uvicorn app:app --host 0.0.0.0 --port 5555 --reload
    # command: tail -f /dev/null
    ports:
      - "5555:5555"
    environment:
      API_DB_CONN_INFO: service=dbalfa9
      PGSERVICEFILE: /var/run/secrets/pgser
      WATCHFILES_FORCE_POLLING: true
    secrets:
      - source: pgser
    restart: always
    
  frontend:
    image: registry.arfima.com/arfima/arfima/uglydata/frontend:latest
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "14080:80"
    restart: always

    depends_on:
      - api

secrets:
  pgser:
    file: ./secrets/postgres/pgser
