FROM ghcr.io/astral-sh/uv:0.7.3-python3.12-bookworm-slim
ARG UV_INDEX

WORKDIR /code

RUN --mount=type=secret,id=UV_EXTRA_INDEX_URL,env=UV_EXTRA_INDEX_URL uv pip install uglyData[api] --break-system-packages --system; 

COPY app.py ./

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5555", "--workers", "8"]
